module.exports = [
  {
    id: 1,
    Title: 'Naruto: Shippûden',
    Year: '2007–2017',
    imdbID: 'tt0988824',
    Genre: 'Animation, Action, Adventure, Comedy, Drama, Fantasy',
    Type: 'series',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTE5NzIwMGUtYTE1MS00MDUxLTgyZjctOWVkZDAxM2M4ZWQ4XkEyXkFqcGdeQXVyNjc2NjA5MTU@._V1_SX300.jpg',
    Director: 'N/A',
    Writer: 'Masashi Kishimoto',
    Actors: 'Junko Takeuchi, Maile Flanagan, Kate Higgins, Chie Nakamura',
    Plot: 'Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition, as well as to become Hokage, who is acknowledged as the leader and strongest of all ninja in the village.'
  },
  {
    id: 2,
    Title: 'The Last: Naruto the Movie',
    Year: '2014',
    imdbID: 'tt3717532',
    Genre: 'Animation, Action, Adventure, Comedy, Romance',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjk1NzA4Njg4Ml5BMl5BanBnXkFtZTgwMDgxODQ5MzE@._V1_SX300.jpg',
    Writer: 'Masashi Kishimoto (original author), Masashi Kishimoto (screen story), Mauro Kyôzuka (screenplay), Seth Walther (english script adaptation)',
    Actors: 'Junko Takeuchi, Nana Mizuki, Jun Fukuyama, Chie Nakamura',
    Plot: "Hinata Hyuga's younger sister has been kidnapped, so Naruto must do what he can to save her."
  },
  {
    id: 3,
    Title: 'Naruto',
    Year: '2002–2007',
    imdbID: 'tt0409591',
    Genre: 'Animation, Action, Adventure, Comedy, Fantasy',
    Type: 'series',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',
    Writer: 'Masashi Kishimoto',
    Actors: 'Junko Takeuchi, Maile Flanagan, Kate Higgins, Chie Nakamura',
    Plot: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja."
  },
  {
    id: 4,
    Title: 'Boruto: Naruto The Movie',
    Year: '2015',
    imdbID: 'tt4618398',
    Genre: 'Animation, Action, Adventure, Comedy',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDIwYjg5YzItZTJmMC00YjJhLWFiNjYtMDU5MmQxOTQxODM2XkEyXkFqcGdeQXVyMjc2Nzg5OTQ@._V1_SX300.jpg',
    Writer: 'Masashi Kishimoto (original author), Masashi Kishimoto (screenplay), Ukyô Kodachi (screenplay cooperation)',
    Actors: 'Yûko Sanpei, Kokoro Kikuchi, Ryûichi Kijima, Junko Takeuchi',
    Plot: "It's been some years since the end of the Shinobi War. Naruto Uzumaki is the 7th Hokage of Konohagakure, in this new era. His son, Boruto Uzumaki, will soon enter the Chûnin exams, alongside Sarada Uchiha and the mysterious Mitsuki."
  },
  {
    id: 5,
    Title: 'Boruto: Naruto Next Generations',
    Year: '2017–',
    imdbID: 'tt6342474',
    Genre: 'Animation, Action, Adventure, Comedy, Drama, Fantasy',
    Type: 'series',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYjM0MDRkYzctMTNhMS00ODYwLTgwMWItZDYxNDlhOGY1YjRlXkEyXkFqcGdeQXVyMzExMzk5MTQ@._V1_SX300.jpg',
    Writer: 'N/A',
    Actors: 'Yûko Sanpei, Kokoro Kikuchi, Ryûichi Kijima, Kenshô Ono',
    Plot: "Son of Naruto Uzumaki, Boruto, follows his father's footsteps along with his friends to become great ninja. Throughout all their adventures, Boruto is determined to make his mark in the ninja world and live outside of his father's shadow."
  },
  {
    id: 6,
    Title: 'Road to Ninja - Naruto the Movie',
    Year: '2012',
    imdbID: 'tt2290828',
    Genre: 'Animation, Action, Adventure, Comedy, Fantasy',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTQ5MTcyNDYwMV5BMl5BanBnXkFtZTgwNzMzNzc0MjE@._V1_SX300.jpg',
    Writer: 'Masashi Kishimoto (manga), Masashi Kishimoto (screen story), Yuka Miyata (screenplay), Junki Takegami (screenplay assistance), Masahiro Hikokubo (screenplay assistance)',
    Actors: 'Junko Takeuchi, Chie Nakamura, Toshiyuki Morikawa, Emi Shinohara',
    Plot: "Naruto and Sakura are captured in a parallel world by Madara, who's intentions are to steal the Nine Tails from Naruto."
  },
  {
    id: 7,
    Title: 'Naruto the Movie: Ninja Clash in the Land of Snow',
    Year: '2004',
    imdbID: 'tt0476680',
    Genre: 'Animation, Action, Adventure, Comedy',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYWFkMTJjODEtMjY2NC00OGRiLThkYjMtMzBjMzVhY2FlZTEyXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_SX300.jpg',
    Writer: 'Masashi Kishimoto (manga series), Katsuyuki Sumizawa (screenplay)',
    Actors: 'Junko Takeuchi, Chie Nakamura, Noriaki Sugiyama, Kazuhiko Inoue',
    Plot: 'Naruto and his team are hired to protect a young actress from three rogue warriors in the Land of the Snow.'
  },
  {
    id: 8,
    Title: 'Naruto Shippuden the Movie: Blood Prison',
    Year: '2011',
    imdbID: 'tt1999167',
    Genre: 'Animation, Action, Comedy, Horror, Mystery, Thriller',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMDgyZmRkYjUtMWExNS00NDQyLTliZTMtOTkwY2M3ZWU0ZjNmXkEyXkFqcGdeQXVyMjc2Nzg5OTQ@._V1_SX300.jpg',
    Writer: 'Akira Higashiyama (screenplay), Masashi Kishimoto (manga)',
    Actors: 'Junko Takeuchi, Chie Nakamura, Rikiya Koyama, Kazuhiko Inoue',
    Plot: 'Naruto Uzumaki is framed and sent to an inescapable prison where he must escape by any means necessary.'
  },
  {
    id: 9,
    Title: 'Naruto Shippûden The Movie: Bonds',
    Year: '2008',
    imdbID: 'tt1160524',
    Genre: 'Animation, Action, Fantasy',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNTE2ODAyNTkxNl5BMl5BanBnXkFtZTgwNTAzMjA2MDE@._V1_SX300.jpg',
    Writer: 'Masashi Kishimoto (creator), Junki Takegami (screenplay)',
    Actors: 'Junko Takeuchi, Chie Nakamura, Noriaki Sugiyama, Unshô Ishizuka',
    Plot: 'A mysterious group of ninja called the Sora-nin from the Sky Country makes a surprise attack on Konoha. This is because Konoha nearly destroyed the Sky Country during the last Shinobi World...'
  },
  {
    id: 10,
    Title: 'Naruto the Movie 2: Legend of the Stone of Gelel',
    Year: '2005',
    imdbID: 'tt0791188',
    Genre: 'Animation, Adventure, Comedy, Drama, Fantasy',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMDE3NjY3Y2MtODE4YS00YzFiLThhMTMtY2Q1NTZkODE4M2NlXkEyXkFqcGdeQXVyNjYwMjkwMjg@._V1_SX300.jpg',
    Writer: 'Hirotsugu Kawasaki (screenplay), Masashi Kishimoto (comic), Yuka Miyata (screenplay)',
    Actors: 'Junko Takeuchi, Shôtarô Morikubo, Chie Nakamura, Gaamon Kai',
    Plot: 'Naruto, Shikamaru and Sakura are on a mission to deliver a lost pet to a village when a mysterious knight appear to confront them.'
  },
  {
    id: 11,
    Title: 'The Avengers',
    Year: '2012',
    imdbID: 'tt0848228',
    Genre: 'Action, Adventure, Sci-Fi',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Writer: 'Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)',
    Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
    Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity."
  },
  {
    id: 12,
    Title: 'Avengers: Infinity War',
    Year: '2018',
    imdbID: 'tt4154756',
    Genre: 'Action, Adventure, Sci-Fi',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg',
    Writer: 'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos,  Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)',
    Actors: 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans',
    Plot: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'
  },
  {
    id: 13,
    Title: 'Avengers: Endgame',
    Year: '2019',
    imdbID: 'tt4154796',
    Genre: 'Action, Adventure, Drama, Sci-Fi',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg',
    Writer: 'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos,  Gamora & Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)',
    Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
    Plot: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe."
  },
  {
    id: 14,
    Title: 'Avengers: Age of Ultron',
    Year: '2015',
    imdbID: 'tt2395427',
    Genre: 'Action, Adventure, Sci-Fi',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg',
    Writer: 'Joss Whedon, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (character created by: Captain America), Jack Kirby (character created by: Captain America), Jim Starlin (character created by: Thanos)',
    Actors: 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans',
    Plot: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan."
  },
  {
    id: 15,
    Title: 'The Avengers',
    Year: '1998',
    imdbID: 'tt0118661',
    Genre: 'Action, Adventure, Sci-Fi, Thriller',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYWE1NTdjOWQtYTQ2Ny00Nzc5LWExYzMtNmRlOThmOTE2N2I4XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg',
    Writer: 'Sydney Newman (television series The Avengers), Don MacPherson',
    Actors: 'Ralph Fiennes, Uma Thurman, Sean Connery, Patrick Macnee',
    Plot: 'Two British Agents team up to stop Sir August de Wynter from destroying the world with a weather-changing machine.'
  },
  {
    id: 16,
    Title: "The Avengers: Earth's Mightiest Heroes",
    Year: '2010–2012',
    imdbID: 'tt1626038',
    Genre: 'Animation, Action, Family, Sci-Fi',
    Type: 'series',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzA4ZjVhYzctZmI0NC00ZmIxLWFmYTgtOGIxMDYxODhmMGQ2XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg',
    Writer: 'N/A',
    Actors: "Eric Loomis, Colleen O'Shaughnessey, Brian Bloom, Rick D. Wasserman",
    Plot: "After 74 villains break out of prison, Marvel's most powerful superheroes team up to capture all of them, and also to defend the Earth from widespread threats.",
    Language: 'English'
  },
  {
    id: 17,
    Title: 'Ultimate Avengers: The Movie',
    Year: '2006',
    imdbID: 'tt0491703',
    Genre: 'Animation, Action, Adventure, Sci-Fi',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_SX300.jpg',
    Writer: 'Mark Millar (comic book: "The Ultimates"), Bryan Hitch (comic book: "The Ultimates"), Greg Johnson (screen story), Boyd Kirkland (screen story), Craig Kyle (screen story), Greg Johnson (screenplay), Christopher L. Yost (additional writing), Joe Simon (comic book & character: Captain America), Jack Kirby (comic book & character: Captain America)',
    Actors: 'Justin Gross, Grey Griffin, Michael Massee, Marc Worden',
    Plot: 'To confront an alien menace, General Fury assembles a team of superheroes lead by a recently resuscitated Captain America.'
  },
  {
    id: 18,
    Title: 'Ultimate Avengers II',
    Year: '2006',
    imdbID: 'tt0803093',
    Genre: 'Animation, Action, Adventure, Sci-Fi',
    Type: 'movie',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Writer: 'Mark Millar (comic book: "The Ultimates"), Bryan Hitch (comic book: "The Ultimates"), Greg Johnson (screen story), Craig Kyle (screen story), Greg Johnson (screenplay), Joe Simon (comic book & character: Captain America), Jack Kirby (comic book & character: Captain America)',
    Actors: 'Justin Gross, Grey Griffin, Michael Massee, Marc Worden',
    Plot: 'When the Chitauri invaders are sighted in the African kingdom of Wakanda, the Avengers covertly enter the advanced nation to investigate.'
  },
  {
    id: 19,
    Title: 'The Avengers',
    Year: '1961–1969',
    imdbID: 'tt0054518',
    Genre: 'Action, Comedy, Crime, Mystery, Romance, Sci-Fi, Thriller',
    Type: 'series',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZWI4ZWM4ZWQtODk1ZC00MzMxLThlZmMtOGFmMTYxZTAwYjc5XkEyXkFqcGdeQXVyMTk0MjQ3Nzk@._V1_SX300.jpg',
    Writer: 'Sydney Newman',
    Actors: 'Patrick Macnee',
    Plot: 'A quirky spy show of the adventures of eccentrically suave British Agent John Steed and his predominately female partners.'
  },
  {
    id: 20,
    Title: 'Avengers Assemble',
    Year: '2013–',
    imdbID: 'tt2455546',
    Genre: 'Animation, Action, Adventure, Sci-Fi',
    Type: 'series',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY0NTUyMDQwOV5BMl5BanBnXkFtZTgwNjAwMTA0MDE@._V1_SX300.jpg',
    Writer: 'Jack Kirby, Joe Simon, Stan Lee',
    Actors: 'Roger Craig Smith, Troy Baker, Fred Tatasciore, Travis Willingham',
    Plot: "The further adventures of the Marvel Universe's mightiest general membership superhero team."
  }
]
